### ISSUE TITLE
Is Five-fold cross validation used in Deep Grasp?

### ISSUE THREAD

**Issue by ZHOUXINWEN** [ivalab/grasp_multiObject#3]
Five fold cross validation appeared in many past grasp detection works. But it is not mentioned in Deep Grasp.

**Comment by fujenchu** [comment]
Yes. Since there is no standard train/test split for Cornell Dataset, we followed [Redmon et al.](https://arxiv.org/abs/1412.3128) for evaluations with five-fold cross validation. Five-fold cross validation has been widely accepted in many prior works for fair comparison. We will add this description to future updates. Thank you very much for pointing this out.

**Comment by ZHOUXINWEN** [comment]
OK,thank you!
